// Copyright © Brett Vickers.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Package ntp provides an implementation of a Simple NTP (SNTP) client
// capable of querying the current time from a remote NTP server.  See
// RFC 5905 (https://tools.ietf.org/html/rfc5905) for more details.
//
// This approach grew out of a go-nuts post by Michael Hofmann:
// https://groups.google.com/forum/?fromgroups#!topic/golang-nuts/FlcdMU5fkLQ
package ntp

import (
	"bytes"
	"crypto/rand"
	"encoding/binary"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"math"
	"net"
	"strconv"
	"strings"
	"time"

	"golang.org/x/net/ipv4"
)

var (
	ErrAuthFailed             = errors.New("authentication MAC verification failed")
	ErrAuthNAK                = errors.New("authentication NAK received")
	ErrExtensionsNotSupported = errors.New("NTPV3 does not support extension fields")
	ErrInvalidAuthKey         = errors.New("invalid authentication key")
	ErrInvalidDispersion      = errors.New("invalid dispersion in response")
	ErrInvalidLeapSecond      = errors.New("invalid leap second in response")
	ErrInvalidMode            = errors.New("invalid mode in response")
	ErrInvalidProtocolVersion = errors.New("invalid protocol version requested")
	ErrInvalidStratum         = errors.New("invalid stratum in response")
	ErrInvalidTime            = errors.New("invalid time reported")
	ErrInvalidTransmitTime    = errors.New("invalid transmit time in response")
	ErrKissOfDeath            = errors.New("kiss of death received")
	ErrServerClockFreshness   = errors.New("server clock not fresh")
	ErrServerNotSynchronized  = errors.New("NTPv5 server not synchronized")
	ErrServerResponseMismatch = errors.New("server response didn't match request")
	ErrServerTickedBackwards  = errors.New("server clock ticked backwards")
)

// Internal constants
const (
	// Protocol constants
	defaultVersion  = 4
	defaultPort     = 123
	defaultTimeout  = 5 * time.Second
	maxDispersion   = 16 * time.Second
	maxPollInterval = (1 << 17) * time.Second
	maxStratum      = 16
	msgSize         = 48

	// Time constants
	nanoPerSec = 1_000_000_000
	timeFormat = "Mon Jan _2 2006  15:04:05.00000000 (MST)"

	// Fixed-point constants (Q*.16, Q*.28, Q*.32)
	mask16 = (1 << 16) - 1     // 0x0000ffff
	mask28 = (1 << 28) - 1     // 0x0fffffff
	mask32 = (1 << 32) - 1     // 0xffffffff
	half16 = (mask16 >> 1) + 1 // 0x00008000
	half28 = (mask28 >> 1) + 1 // 0x08000000
	half32 = (mask32 >> 1) + 1 // 0x80000000
)

// The LeapIndicator is used to warn if a leap second should be inserted
// or deleted in the last minute of the current month.
type LeapIndicator uint8

const (
	// LeapNoWarning indicates that no leap second will be inserted in the
	// near future (within the next 14 days for NTPv5). It is also used when
	// responding to an NTPv5 leap-smeared timescale request.
	LeapNoWarning LeapIndicator = 0 + iota

	// LeapAddSecond indicates that, in the near future (within 14 days for
	// NTPv5), a leap second will be inserted at the end of the current month.
	LeapAddSecond

	// LeapDelSecond indicates that, in the near future (within 14 days for
	// NTPv5), a leap second will be deleted at the end of the current month.
	LeapDelSecond

	// LeapNotInSync indicates that the server has no time source or other
	// source providing information about leap seconds (often due to an
	// unsynchronized server clock).
	LeapNotInSync
)

// An Extension adds custom behaviors capable of modifying NTP packets before
// being sent to the server and processing packets after being received by the
// server.
type Extension interface {
	// ProcessQuery is called when the client is about to send a query to the
	// NTP server. The buffer contains the NTP message and any extension
	// fields generated by this package (excluding the NTPv5 MAC and
	// correction extension fields). It may also contain extension fields
	// added by other extensions processed prior to this one.
	ProcessQuery(buf *bytes.Buffer) error

	// ProcessResponse is called after the client has received the server's
	// NTP response. The buffer contains the entire message returned by the
	// server.
	ProcessResponse(buf []byte) error
}

// QueryOptions contains configurable options used by the QueryWithOptions
// function.
type QueryOptions struct {
	// Timeout determines how long the client waits for a response from the
	// server before failing with a timeout error. Defaults to 5 seconds.
	Timeout time.Duration

	// Version of the NTP protocol to use. Defaults to 4. Allowed values
	// include 3, 4, and 5. The IETF has not finalized version 5 of the NTP
	// protocol, so version 5 support is considered experimental and should
	// not be used in production.
	Version int

	// LocalAddress contains the local IP address to use when creating a
	// connection to the remote NTP server. This may be useful when the local
	// system has more than one IP address. This address should not contain
	// a port number.
	LocalAddress string

	// TTL specifies the maximum number of IP hops before the query datagram
	// is dropped by the network. Defaults to the local system's default value.
	TTL int

	// Timescale is used to request timestamps from the server that are
	// measured according to a specific timescale reference (UTC, TAI, UT1, or
	// leap-smeared UTC). Defaults to TimescaleUTC. Used only in NTPv5.
	Timescale Timescale

	// AdditionalTimescales requests additional timestamps using the specified
	// timescales, allowing the client to determine the offsets between the
	// primary timescale (specified in the Timescale field) and each of the
	// additional timescales. If the server supports this feature, offsets
	// will be reported in the response's TimescaleOffsets field. Used only in
	// NTPv5.
	AdditionalTimescales []Timescale

	// ServerCookie contains the server cookie returned by a prior server
	// response when operating in interleaved mode. Used only in NTPv5.
	ServerCookie uint64

	// Auth contains the options used to configure symmetric key
	// authentication. See RFC 5905 for further details. For NTPv3 and NTPv4,
	// this results in a MAC or digest being appended to the end of the NTP
	// message. For NTPv5, this results in a message authentication extension
	// field being added to the NTP message. Defaults to no symmetric key
	// authentication.
	Auth AuthOptions

	// Extensions may be provided in order to (a) modify NTP queries before
	// they are transmitted and (b) process NTP responses after they arrive.
	// When building an NTP request, these extensions are processed in the
	// order listed. When processing a server response, they are processed in
	// reverse order. An example of an extension is one that implements
	// Network Time Security (NTS). See: https://github.com/beevik/nts.
	Extensions []Extension

	// GetSystemTime is a callback used to override the default method of
	// obtaining the local system time during time synchronization. If not
	// specified, time.Now is used.
	GetSystemTime func() time.Time

	// RequestReferenceID is a struct used to request reference ID bloom
	// filter values, which are returned in the ReferenceIDFilterValues field
	// of the response. Used only in NTPv5.
	RequestReferenceID ReferenceIDRequest

	// RequestSupportedVersions indicates whether to request the versions of
	// the NTP protocol supported by the server. When used with NTPv5, the
	// response will list all supported versions. When used with NTPv3 or
	// NTPv4, the response's ReferenceTime value will be invalid, and the
	// supported version list will include the version used in the query as
	// well as 5 if the server supports it.
	RequestSupportedVersions bool

	// RequestCorrection indicates whether to request delay corrections from
	// network switches and routers along the path between the client and the
	// server. If available, such delay corrections will be applied to the
	// response's ClockOffset, making it more accurate. Used only in NTPv5.
	RequestCorrection bool

	// RequestReferenceTime indicates whether to request that the server
	// include a reference timestamp in its response. Used only in NTPv5.
	RequestReferenceTime bool

	// RequestMonotonic indicates whether to request a second receive
	// timestamp from the server using an independent monotonic clock without
	// phase correction. This second timestamp is intended to be used by the
	// client to reduce clock drift by adjusting the frequency of its local
	// system clock. Used only in NTPv5.
	RequestMonotonic bool

	// RequestInterleavedMode indicates whether to use interleaved mode for
	// the NTPv5 query. Used in conjunction with the ServerCookie field. Used
	// only in NTPv5.
	RequestInterleavedMode bool

	// Dialer is a callback used to override the default UDP network dialer.
	// The localAddress is directly copied from the LocalAddress field
	// specified in QueryOptions. It may be the empty string or a host address
	// (without port number). The remoteAddress is the "host:port" string
	// derived from the first parameter to QueryWithOptions. The remoteAddress
	// is guaranteed to include a port number.
	Dialer func(localAddress, remoteAddress string) (net.Conn, error)

	// DEPRECATED. Use Dialer instead.
	Dial func(laddr string, lport int, raddr string, rport int) (net.Conn, error)

	// DEPRECATED. Embed the port number in the query address string instead.
	Port int
}

// The ReferenceIDRequest struct is included in QueryOptions to request a
// chunk of reference ID bloom filter values. Used only in NTPv5. See IETF
// draft-ietf-ntp-ntpv5 section 7.4 for futher details.
type ReferenceIDRequest struct {
	// The octet offset of the reference ID filter chunk to request. Must be
	// less than or equal to 512.
	ChunkOffset uint16

	// The number of octets in the requested reference ID filter chunk. The
	// sum of ChunkOffset and ChunkSize must be less than or equal to 512.
	ChunkSize uint16
}

// A Response contains time data, some of which is returned by the NTP server
// and some of which is calculated by the client.
type Response struct {
	// ClockOffset is the estimated offset of the local system clock relative
	// to the server's clock. Add this value to subsequent local system clock
	// times in order to obtain a time that is synchronized to the server's
	// clock.
	ClockOffset time.Duration

	// RTT is the measured round-trip-time delay estimate between the client
	// and the server.
	RTT time.Duration

	// Timestamps contains the four NTP protocol timestamps used to calculate
	// ClockOffset and RTT.
	Timestamps ProtocolTimestamps

	// Precision is the reported precision of the server's clock.
	Precision time.Duration

	// Version is the NTP protocol version number reported by the server.
	// Supported values include 3, 4, and 5.
	Version int

	// Stratum is the "stratum level" of the server. The smaller the number,
	// the closer the server is to the reference clock. Stratum 1 servers are
	// attached directly to the reference clock. For NTPv3 and NTPv4, a
	// stratum value of 0 indicates the "kiss of death," which typically
	// occurs when the client issues too many requests to the server in a
	// short period of time.
	Stratum uint8

	// Timescale reports the timescale used by the server to timestamp
	// messages it sent and received. Always TimescaleUTC for NTPv3 and NTPv4.
	Timescale Timescale

	// TimescaleOffsets contains the time offsets of any requested additional
	// timescales relative to the primary timescale. Used only in NTPv5.
	TimescaleOffsets []TimescaleOffset

	// Era is the NTP era number returned by the server. Era 0 spans
	// 1900-2036, Era 1 spans 2036-2172, etc.
	Era uint8

	// ReferenceID is a 32-bit integer used to help identify which server or
	// reference clock generated the reported time. For stratum 1 servers,
	// this is typically a meaningful zero-padded ASCII-encoded string
	// assigned to the clock. For stratum 2+ servers, this is a reference
	// identifier for the server and is either the server's IPv4 address or a
	// hash of its IPv6 address. For kiss-of-death responses (stratum 0), this
	// is the ASCII-encoded "kiss code". Used only in NTPv3 and NTPv4.
	ReferenceID uint32

	// ReferenceIDFilterValues contains the requested chunk of reference ID
	// bloom filter values. The size and offset of this chunk are determined
	// by the ReferenceIDRequest field in QueryOptions. Used only in NTPv5.
	ReferenceIDFilterValues []byte

	// ReferenceTime is the time the server last updated its local clock. In
	// NTPv3 and NTPv4, this value is always returned by the server. In NTPv5,
	// it is returned only when requested via the RequestReferenceTime field
	// in QueryOptions.
	ReferenceTime time.Time

	// MonotonicOffset contains the offset of the server's monotonic clock
	// relative to its primary clock. It is calculated by taking the
	// difference between the monotonic receive timestamp and the primary
	// receive timestamp contained in the response packet. Returned only when
	// requested via the RequestMonotonic field in QueryOptions. Used only in
	// NTPv5.
	MonotonicOffset time.Duration

	// MonotonicEpochID is the an identifier associated with the
	// MonotonicOffset value. Whenever this value changes, the server's
	// monotonic clock has been phase-corrected, and any frequency adjustment
	// algorithms running on the client must be reset. Returned only when
	// requested via the RequestMonotonic field in QueryOptions. Used only in
	// NTPv5.
	MonotonicEpochID uint32

	// Correction contains delay correction information provided by network
	// switches and routers along the path between the client and the server.
	// Populated only when supported by the network equipment along the path
	// and when requested via the QueryOptions RequestCorrection field. Used
	// only in NTPv5.
	Correction Correction

	// SupportedVersions contains an array of NTP protocol version numbers
	// supported by the server. Populated if requested by the
	// RequestSupportedVersions field in QueryOptions. Used only in NTPv5.
	SupportedVersions []int

	// RootDelay is the server's estimated aggregate round-trip-time delay to
	// the stratum 1 server.
	RootDelay time.Duration

	// RootDispersion is the server's estimated maximum measurement error
	// relative to the stratum 1 server.
	RootDispersion time.Duration

	// RootDistance is an estimate of the total synchronization distance
	// between the client and the stratum 1 server.
	RootDistance time.Duration

	// Leap indicates whether a leap second should be added or removed from
	// the current month's last minute.
	Leap LeapIndicator

	// MinError is a lower bound on the "causality violation" between the
	// client and server clocks when they are not yet synchronized.
	MinError time.Duration

	// KissCode is a 4-character string describing the reason for a "kiss of
	// death" response (stratum=0). Used only in NTPv3 and NTPv4. For a list
	// of standard kiss codes, see:
	// https://tools.ietf.org/html/rfc5905#section-7.4.
	KissCode string

	// Poll is the maximum interval between successive NTP query messages to
	// the server.
	Poll time.Duration

	// Flags reported by the server.
	Flags ResponseFlags

	// ServerCookie is the cookie returned by an NTPv5 server. In interleaved
	// mode, this cookie should be passed to the server in the next query.
	// Used only in NTPv5.
	ServerCookie uint64

	// DEPRECATED. Use Timestamps.ServerXmit instead.
	Time time.Time

	authErr error
}

// ProtocolTimestamps contains the four timestamps used by the NTP protocol to
// calculate clock offset and round-trip delay.
type ProtocolTimestamps struct {
	// ClientXmit is the timestamp recorded by the client when it transmitted
	// the request.
	ClientXmit time.Time

	// ServerRecv is the timestamp recorded by the server when it received the
	// request.
	ServerRecv time.Time

	// ServerXmit is the timestamp recorded by the server when it transmitted
	// the response.
	ServerXmit time.Time

	// ClientRecv is the timestamp recorded by the client when it received the
	// response.
	ClientRecv time.Time
}

// The TimescaleOffset struct contains a timescale identifier and its
// corresponding offset relative to the primary timescale specified in the
// QueryOptions Timescale field. Used only in NTPv5.
type TimescaleOffset struct {
	// The Timescale to which this offset pertains.
	Timescale Timescale

	// The offset of the timescale relative to the request's primary
	// timescale. This value may be added to the response's ClockOffset to
	// obtain a time synchronized to the associated timescale.
	Offset time.Duration
}

// DelayUnrepresentable is a sentinel value used to indicate that a delay
// correction value (i.e., OriginDelay or ReturnDelay) is not representable.
// This occurs when a correction exceeds the maximum value representable by
// NTP's correction timestamp format.
var DelayUnrepresentable = time.Duration(math.MinInt64)

// The Correction struct contains delay correction information provided by
// network switches and routers along the path between the client and the
// server. Used only in NTPv5.
type Correction struct {
	// OriginDelay is the total delay correction accumulated by the request
	// packet on its way from the originating client to the server.
	OriginDelay time.Duration

	// OriginPathID is the path identifier calculated by intermediate nodes on
	// the request packet's path from the originating client to the server.
	OriginPathID uint16

	// ReturnDelay is the total delay correction accumulated by the response
	// packet on its return from the server to the client.
	ReturnDelay time.Duration

	// ReturnPathID is the path identifier calculated by intermediate nodes on
	// the response packet's return from the server to the client. This may be
	// compared to the OriginPathID to determine if the request and response
	// packets traversed the same network path.
	ReturnPathID uint16
}

// ResponseFlags are flag bits reported by an NTPv5 server in its response.
type ResponseFlags uint32

const (
	// FlagSynchronized indicates whether the server is currently synchronized
	// to a reference clock. For NTPv3 and NTPv4, this flag is set when the
	// returned stratum is valid. For NTPv5, it is set only when the server
	// explicitly indicates synchronization.
	FlagSynchronized ResponseFlags = 1 << iota

	// FlagInterleaved indicates whether the server reported its response in
	// interleaved mode. Only used in NTPv5.
	FlagInterleaved
)

// IsKissOfDeath returns true if the response is a "kiss of death" from the
// remote server. If this function returns true, you may examine the
// response's KissCode value to determine the reason for the kiss of death.
// Valid only for NTPv3 and NTPv4.
func (r *Response) IsKissOfDeath() bool {
	return r.Version < 5 && r.Stratum == 0
}

// Log outputs a human-readable representation of the NTP response to the
// provided io.Writer. Meant for debugging purposes.
func (r *Response) Log(w io.Writer) {
	now := time.Now().Local()
	fmt.Fprintf(w, "    Version: %d\n", r.Version)
	fmt.Fprintf(w, "ClockOffset: %s\n", r.ClockOffset)
	fmt.Fprintf(w, "        RTT: %s\n", r.RTT)
	fmt.Fprintf(w, " SystemTime: %s\n", fmtTime(now))
	fmt.Fprintf(w, "  ~TrueTime: %s\n", fmtTime(now.Add(r.ClockOffset)))
	fmt.Fprintf(w, " ClientXmit: %s\n", fmtTime(r.Timestamps.ClientXmit))
	fmt.Fprintf(w, " ServerRecv: %s\n", fmtTime(r.Timestamps.ServerRecv))
	fmt.Fprintf(w, " ServerXmit: %s\n", fmtTime(r.Timestamps.ServerXmit))
	fmt.Fprintf(w, " ClientRecv: %s\n", fmtTime(r.Timestamps.ClientRecv))
	fmt.Fprintf(w, "    Stratum: %d\n", r.Stratum)
	fmt.Fprintf(w, "       Leap: %s\n", fmtLeap(r.Leap))
	fmt.Fprintf(w, "      Flags: %s\n", fmtFlags(r.Flags))
	fmt.Fprintf(w, "        Era: %d\n", r.Era)
	fmt.Fprintf(w, "  Timescale: %s\n", fmtTimescale(r.Timescale))
	fmt.Fprintf(w, "       Poll: %s\n", r.Poll)
	fmt.Fprintf(w, "  Precision: %s\n", r.Precision)
	fmt.Fprintf(w, "  RootDelay: %s\n", r.RootDelay)
	fmt.Fprintf(w, "   RootDisp: %s\n", r.RootDispersion)
	fmt.Fprintf(w, "   RootDist: %s\n", r.RootDistance)
	fmt.Fprintf(w, "  Supported: %v\n", r.SupportedVersions)
	fmt.Fprintf(w, "   MinError: %s\n", r.MinError)
	fmt.Fprintf(w, "    RefTime: %s\n", fmtTime(r.ReferenceTime))
	if r.Version == 5 {
		fmt.Fprintf(w, " RefIDBytes: %s\n", fmtRefIDFilter(r.ReferenceIDFilterValues))
		fmt.Fprintf(w, " Correction: %s\n", fmtCorrection(r.Correction))
		fmt.Fprintf(w, "    Offsets: %s\n", fmtTimescaleOffsets(r.TimescaleOffsets))
		fmt.Fprintf(w, " MonoOffset: %s\n", r.MonotonicOffset)
		fmt.Fprintf(w, "  MonoEpoch: %s\n", fmtEpoch(r.MonotonicEpochID))
		fmt.Fprintf(w, "  SrvCookie: %s", fmtCookie(r.ServerCookie))
	} else {
		fmt.Fprintf(w, "      RefID: %s (0x%08x)\n", r.ReferenceString(), r.ReferenceID)
		fmt.Fprintf(w, "   KissCode: %s", fmtKissCode(r.KissCode))
	}
}

// ReferenceString returns the response's ReferenceID value formatted as a
// string. If the response's stratum is zero, then the "kiss o' death" string
// is returned. If stratum is one, then the server is a reference clock and
// the reference clock's name is returned. If stratum is two or greater, then
// the ID is either an IPv4 address or an MD5 hash of the IPv6 address; in
// either case the reference string is reported as 4 dot-separated
// decimal-based integers. Valid only for NTPv3 and NTPv4.
func (r *Response) ReferenceString() string {
	if r.Version == 5 {
		return ""
	}

	if r.Stratum == 0 {
		return kissCode(r.ReferenceID)
	}

	var b [4]byte
	binary.BigEndian.PutUint32(b[:], r.ReferenceID)

	if r.Stratum == 1 {
		const dot = rune(0x22c5)
		var r []rune
		for i := range b {
			if b[i] == 0 {
				break
			}
			if b[i] >= 32 && b[i] <= 126 {
				r = append(r, rune(b[i]))
			} else {
				r = append(r, dot)
			}
		}
		return fmt.Sprintf(".%s.", string(r))
	}

	return fmt.Sprintf("%d.%d.%d.%d", b[0], b[1], b[2], b[3])
}

// Validate checks if the response is valid for the purposes of time
// synchronization.
func (r *Response) Validate() error {
	// Forward authentication errors.
	if r.authErr != nil {
		return r.authErr
	}

	// Handle NTPv5 unsynchronized server.
	if r.Version >= 5 && r.Flags&FlagSynchronized == 0 {
		return ErrServerNotSynchronized
	}

	// Handle invalid stratum values.
	if r.Version < 5 && r.Stratum == 0 {
		return ErrKissOfDeath
	}
	if r.Stratum >= maxStratum {
		return ErrInvalidStratum
	}

	// Estimate the "freshness" of the time. If it exceeds the maximum polling
	// interval (~36 hours), then it cannot be considered "fresh".
	if (r.Version < 5 && r.ReferenceTime != ntpEra0) || (r.Version == 5 && !r.ReferenceTime.IsZero()) {
		if freshness := r.Time.Sub(r.ReferenceTime); freshness > maxPollInterval {
			return ErrServerClockFreshness
		}
	}

	// Calculate the peer synchronization distance, lambda:
	//  	lambda := RootDelay/2 + RootDispersion
	// If this value exceeds MAXDISP (16s), then the time is not suitable
	// for synchronization purposes.
	// https://tools.ietf.org/html/rfc5905#appendix-A.5.1.1.
	lambda := r.RootDelay/2 + r.RootDispersion
	if lambda > maxDispersion {
		return ErrInvalidDispersion
	}

	// If the server's transmit time is before its reference time, the
	// response is invalid.
	if r.Time.Before(r.ReferenceTime) {
		return ErrInvalidTime
	}

	// Handle invalid leap second indicator.
	if r.Version < 5 && r.Leap == LeapNotInSync {
		return ErrInvalidLeapSecond
	}

	// nil means the response is valid.
	return nil
}

// Query requests time data from a remote NTP server. The response contains
// information from which a more accurate local time can be inferred.
//
// The server address is of the form "host", "host:port", "host%zone:port",
// "[host]:port" or "[host%zone]:port". The host may contain an IPv4, IPv6 or
// domain name address. When specifying both a port and an IPv6 address, one
// of the bracket formats must be used. If no port is included, NTP default
// port 123 is used.
func Query(address string) (*Response, error) {
	return QueryWithOptions(address, QueryOptions{})
}

// QueryWithOptions performs the same function as Query but allows for the
// customization of certain query behaviors. See the comments for Query and
// QueryOptions for further details.
func QueryWithOptions(remoteAddress string, opt QueryOptions) (*Response, error) {
	if opt.Version == 0 {
		opt.Version = defaultVersion
	}
	if opt.Version < 3 || opt.Version > 5 {
		return nil, ErrInvalidProtocolVersion
	}

	if opt.Timeout == 0 {
		opt.Timeout = defaultTimeout
	}
	if opt.Port == 0 {
		opt.Port = defaultPort
	}
	if opt.GetSystemTime == nil {
		opt.GetSystemTime = func() time.Time { return time.Now().UTC() }
	}
	if opt.Dial != nil {
		// wrapper for the deprecated Dial callback.
		opt.Dialer = func(la, ra string) (net.Conn, error) {
			return dialWrapper(la, ra, opt.Dial)
		}
	}
	if opt.Dialer == nil {
		opt.Dialer = defaultDialer
	}

	// Compose a conforming host:port remote address string, adding the port
	// number if necessary.
	remoteAddress, err := fixHostPort(remoteAddress, opt.Port)
	if err != nil {
		return nil, err
	}

	// Connect to the NTP server.
	conn, err := opt.Dialer(opt.LocalAddress, remoteAddress)
	if err != nil {
		return nil, err
	}
	defer conn.Close()

	// Attempt to enable hardware timestamping for more accurate receive
	// timestamps.
	err = enableHardwareTimestamps(conn)
	if err != nil {
		return nil, err
	}

	// Set a TTL for the packet if requested.
	if opt.TTL != 0 {
		ipcon := ipv4.NewConn(conn)
		err = ipcon.SetTTL(opt.TTL)
		if err != nil {
			return nil, err
		}
	}

	// Set a timeout on the connection.
	conn.SetDeadline(time.Now().Add(opt.Timeout))

	// Perform the version-specific query. NTPv3 and NTPv4 share nearly
	// the same client implementation, so use queryV4 for both.
	if opt.Version == 5 {
		return queryV5(conn, &opt)
	} else {
		return queryV4(conn, &opt)
	}
}

// Time returns the current, corrected local time using information returned
// from the remote NTP server. On error, Time returns the uncorrected local
// system time. This function can only be used with NTPv3 and NTPv4 servers.
//
// The server address is of the form "host", "host:port", "host%zone:port",
// "[host]:port" or "[host%zone]:port". The host may contain an IPv4, IPv6 or
// domain name address. When specifying both a port and an IPv6 address, one
// of the bracket formats must be used. If no port is included, NTP default
// port 123 is used.
func Time(address string) (time.Time, error) {
	r, err := Query(address)
	if err != nil {
		return time.Now(), err
	}

	err = r.Validate()
	if err != nil {
		return time.Now(), err
	}

	// Use the response's clock offset to calculate an accurate time.
	return time.Now().Add(r.ClockOffset), nil
}

// dialWrapper is used to wrap the deprecated Dial callback in QueryOptions.
func dialWrapper(la, ra string,
	dial func(la string, lp int, ra string, rp int) (net.Conn, error)) (net.Conn, error) {
	rhost, rport, err := net.SplitHostPort(ra)
	if err != nil {
		return nil, err
	}

	rportValue, err := strconv.Atoi(rport)
	if err != nil {
		return nil, err
	}

	return dial(la, 0, rhost, rportValue)
}

// defaultDialer provides a UDP dialer based on Go's built-in net stack.
func defaultDialer(localAddress, remoteAddress string) (net.Conn, error) {
	var laddr *net.UDPAddr
	if localAddress != "" {
		var err error
		laddr, err = net.ResolveUDPAddr("udp", net.JoinHostPort(localAddress, "0"))
		if err != nil {
			return nil, err
		}
	}

	raddr, err := net.ResolveUDPAddr("udp", remoteAddress)
	if err != nil {
		return nil, err
	}

	return net.DialUDP("udp", laddr, raddr)
}

// fixHostPort examines an address in one of the accepted forms and modifies
// it to include a port number if necessary.
func fixHostPort(address string, defaultPort int) (fixed string, err error) {
	if len(address) == 0 {
		return "", errors.New("address string is empty")
	}

	// If the address is wrapped in brackets, append a port if necessary.
	if address[0] == '[' {
		end := strings.IndexByte(address, ']')
		switch {
		case end < 0:
			return "", errors.New("missing ']' in address")
		case end+1 == len(address):
			return fmt.Sprintf("%s:%d", address, defaultPort), nil
		case address[end+1] == ':':
			return address, nil
		default:
			return "", errors.New("unexpected character following ']' in address")
		}
	}

	// No colons? Must be a port-less IPv4 or domain address.
	last := strings.LastIndexByte(address, ':')
	if last < 0 {
		return fmt.Sprintf("%s:%d", address, defaultPort), nil
	}

	// Exactly one colon? A port have been included along with an IPv4 or
	// domain address. (IPv6 addresses are guaranteed to have more than one
	// colon.)
	prev := strings.LastIndexByte(address[:last], ':')
	if prev < 0 {
		return address, nil
	}

	// Two or more colons means we must have an IPv6 address without a port.
	return fmt.Sprintf("[%s]:%d", address, defaultPort), nil
}

// NTP eras
var (
	ntpEra0      = time.Date(1900, 1, 1, 0, 0, 0, 0, time.UTC)
	ntpEra1      = time.Date(2036, 2, 7, 6, 28, 16, 0, time.UTC)
	ntpEraLength = time.Duration(int64(time.Second) << 32)
)

// getEra determines the NTP era for the provided time.
func getEra(t time.Time) int64 {
	ntpSec := uint64(t.Unix() - ntpEra0.Unix())
	return int64(ntpSec >> 32)
}

// offset calculates an uncorrected clock offset using the four NTP
// timestamps.
func offset(t1, t2, t3, t4 time.Time) time.Duration {
	return (t2.Sub(t1) + t3.Sub(t4)) / 2
}

// rtt calculates the round-trip-time delay using the four NTP timestamps.
func rtt(t1, t2, t3, t4 time.Time) time.Duration {
	return max(t4.Sub(t1)-t3.Sub(t2), 0)
}

// minError calculates a lower bound on the "causality violation" detected
// between the client and server clocks when they are not yet synchronized.
func minError(t1, t2, t3, t4 time.Time) time.Duration {
	// rtt    = (t4 - t1) - (t3 - t2)
	// offset = ((t2 - t1) + (t3 - t4)) / 2
	//
	// t2 - t1 = rtt/2 + offset
	// t4 - t3 = rtt/2 - offset
	//
	// If the client and server clocks are synchronized, then the offset
	// should be roughly zero and the timestamp differences should be roughly
	// equal to the one-way trip time (rtt/2). If the clocks are not
	// synchronized, then the magnitude of the offset relative to the one-way
	// trip time provides a lower bound on the "causality violation" between
	// the two clocks.

	offset := offset(t1, t2, t3, t4)
	if offset < 0 {
		offset = -offset
	}

	rtt := rtt(t1, t2, t3, t4)
	ott := rtt / 2

	if offset > ott {
		return offset - ott
	}
	return 0
}

// rootDistance estimates the root distance between the client and the stratum
// 1 server.
func rootDistance(rtt, rootDelay, rootDisp time.Duration) time.Duration {
	// The root distance is:
	// 	the maximum error due to all causes of the local clock
	//	relative to the primary server. It is defined as half the
	//	total delay plus total dispersion plus peer jitter.
	//	(https://tools.ietf.org/html/rfc5905#appendix-A.5.5.2)
	//
	// In the reference implementation, it is calculated as follows:
	//	rootDist = max(MINDISP, rootDelay + rtt)/2 + rootDisp
	//			+ peerDisp + PHI * (uptime - peerUptime)
	//			+ peerJitter
	// For an SNTP client which sends only a single packet, most of these
	// terms are irrelevant and become 0.
	totalDelay := rtt + rootDelay
	return totalDelay/2 + rootDisp
}

// randUint64 creates a random non-zero 64-bit cookie value.
func randUint64() (uint64, error) {
	for range 4 {
		var cookieBytes [8]byte
		_, err := rand.Read(cookieBytes[:])
		if err != nil {
			return 0, err
		}

		cookie := binary.BigEndian.Uint64(cookieBytes[:])
		if cookie != 0 {
			return cookie, nil
		}
	}
	return 0, errors.New("failed to generate non-zero random value")
}

// An timestamp is a 64-bit fixed-point (Q32.32) representation of the
// number of seconds elapsed.
type timestamp uint64

// Duration interprets the fixed-point timestamp as a number of elapsed
// seconds and returns the corresponding time.Duration value.
func (t timestamp) Duration() time.Duration {
	t0 := uint64(t>>32) * nanoPerSec
	f1 := uint64(t&mask32) * nanoPerSec
	t1 := f1 >> 32
	t1 += uint64((f1&mask32)+half32) >> 32 // round half up
	return time.Duration(t0 + t1)
}

// Time interprets a timestamp value as an absolute time, using the provided
// era number to disambiguate the time period.
func (t timestamp) Time(era uint8) time.Time {
	eraStart := ntpEra0.Add(time.Duration(era) * ntpEraLength)
	return eraStart.Add(t.Duration())
}

// TimeV4 interprets the NTPv3/NTPv4 timestamp value as an absolute time and
// returns the corresponding time.Time value.
func (t timestamp) TimeV4() time.Time {
	if inferEra(t) == 1 {
		return ntpEra1.Add(t.Duration())
	}
	return ntpEra0.Add(t.Duration())
}

// inferEra infers an NTP era from a timestamp value. This function is used
// only for NTPv3 and NTPv4 timestamps.
func inferEra(t timestamp) uint8 {
	// Assume NTP era 1 (year 2036+) if the raw timestamp suggests a year
	// before 1970. Otherwise assume NTP era 0. This allows us to properly
	// handle the rollover from era 0 to 1 when converting timestamps to
	// times.
	const t1970 = 0x83aa_7e80_0000_0000
	if uint64(t) < t1970 {
		return 1
	}
	return 0
}

// toTimestamp converts a Time value into its 64-bit fixed-point timestamp
// representation.
func toTimestamp(t time.Time) timestamp {
	era := getEra(t)
	eraStart := ntpEra0.Add(time.Duration(era) * ntpEraLength)

	nsec := uint64(t.Sub(eraStart))
	sec := nsec / nanoPerSec

	remainder := nsec - sec*nanoPerSec
	remainderShifted := remainder << 32
	frac := (remainderShifted + nanoPerSec/2) / nanoPerSec
	return timestamp(sec<<32 | frac)
}

// toInterval converts an NTP poll interval exponent into a time.Duration.
func toInterval(t int8) time.Duration {
	switch {
	case t > 0:
		return time.Duration(int64(time.Second) << int(t))
	case t < 0:
		return time.Duration(int64(time.Second) >> int(-t))
	default:
		return time.Second
	}
}

func fmtCookie(c uint64) string {
	if c == 0 {
		return "<zero>"
	}
	return fmt.Sprintf("0x%016x", c)
}

func fmtCorrection(c Correction) string {
	if c.OriginDelay < 0 || c.ReturnDelay < 0 {
		return "<invalid>"
	}
	if c.OriginPathID == 0 && c.ReturnPathID == 0 {
		return "<none>"
	}
	return fmt.Sprintf("%s (0x%04x) / %s (0x%04x)",
		c.OriginDelay, c.OriginPathID,
		c.ReturnDelay, c.ReturnPathID)
}

func fmtEpoch(epoch uint32) string {
	if epoch == 0 {
		return "<zero>"
	}
	return fmt.Sprintf("0x%08x", epoch)
}

func fmtKissCode(s string) string {
	if s == "" {
		return "<empty>"
	}
	return s
}

func fmtLeap(li LeapIndicator) string {
	switch li {
	case LeapNoWarning:
		return "No Warning"
	case LeapAddSecond:
		return "Add Second"
	case LeapDelSecond:
		return "Delete Second"
	default:
		return "Unknown"
	}
}

func fmtRefIDFilter(filter []byte) string {
	if filter == nil {
		return "<nil>"
	}
	l := min(len(filter), 24)
	return "0x" + hex.EncodeToString(filter[:l]) + "..."
}

func fmtFlags(flags ResponseFlags) string {
	ftab := map[ResponseFlags]string{
		FlagSynchronized: "Synchronized",
		FlagInterleaved:  "Interleaved",
	}

	copy := flags
	var s strings.Builder
	s.WriteString("[")
	for flags != 0 {
		f := flags & -flags
		if s.Len() > 1 {
			s.WriteString(" ")
		}
		if ss, ok := ftab[f]; ok {
			s.WriteString(ss)
		} else {
			s.WriteString("Unknown")
		}
		flags &= ^f
	}
	fmt.Fprintf(&s, "] (0x%08x)", uint32(copy))
	return s.String()
}

func fmtTime(value time.Time) string {
	if value.Equal(ntpEra0) {
		return "<invalid>"
	}
	return value.Format(timeFormat)
}

func fmtTimescale(ts Timescale) string {
	switch ts {
	case TimescaleUTC:
		return "UTC"
	case TimescaleTAI:
		return "TAI"
	case TimescaleUT1:
		return "UT1"
	case TimescaleUTCSmeared:
		return "UTC(smeared)"
	default:
		return "Unknown"
	}
}

func fmtTimescaleOffset(o TimescaleOffset) string {
	return fmt.Sprintf("%s=%v", fmtTimescale(o.Timescale), o.Offset)
}

func fmtTimescaleOffsets(offsets []TimescaleOffset) string {
	if offsets == nil {
		return "<none>"
	}

	var s strings.Builder
	s.WriteString("[")
	for i, o := range offsets {
		if i > 0 {
			s.WriteString(", ")
		}
		s.WriteString(fmtTimescaleOffset(o))
	}
	s.WriteString("]")

	return s.String()
}
